global using UserManagementWithIdentity.Models;
global using UserManagementWithIdentity.ViewModels;
global using UserManagementWithIdentity.Services;
global using Microsoft.AspNetCore.Identity;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity.UI.Services;